Auth designs
KenyaFlutterDev/droidcon_2022_flutter pull request #13
Opened 2022-09-14 10:10 UTC by sababuvercetti

This pull request features the following designs implementation. 
- The splash screen
- The sign in screen
- The sign up screen
- The theme switcher dialod

This is as shown in the screenshots below

![Screenshot_1663150039](https://user-images.githubusercontent.com/35136541/190126483-827c9fa8-22ed-421b-8197-1f677ddfdd42.png)
![Screenshot_1663150035](https://user-images.githubusercontent.com/35136541/190126498-6f739558-22a5-485d-a05b-44747e61d0be.png)
![Screenshot_1663150022](https://user-images.githubusercontent.com/35136541/190126505-0c9cda50-04e8-4d49-9035-9307218deb09.png)
![Screenshot_1663150018](https://user-images.githubusercontent.com/35136541/190126512-97a320b9-9ea2-4555-9fb9-0c058a1b178b.png)
![Screenshot_1663150009](https://user-images.githubusercontent.com/35136541/190126516-9db2693f-9897-4fd9-b458-cbadf0819c0e.png)
![Screenshot_1663150006](https://user-images.githubusercontent.com/35136541/190126519-4887afa4-793f-4b17-a884-f2d9932a1553.png)

2022-09-18 19:16 UTC, KendiJ approved these changes
Seen

2022-09-18 21:39 UTC, EricRootLee requested changes
Fix conflicts

2022-09-25 12:19 UTC, ndungudedan commented
Can this be merged? 
It does have common things already setup.

2022-09-28 15:48 UTC, EricRootLee requested changes

2022-09-28 15:48 UTC, EricRootLee commented on lib/router/router.dart
> +    // FirebaseAnalyticsObserver(analytics: FirebaseAnalytics.instance),
Removed if not used

2022-09-28 15:48 UTC, EricRootLee commented on lib/user_interfaces/splash/splash_screen.dart
> +      // ignore: use_build_context_synchronously
Removed if not used

2022-09-28 15:48 UTC, EricRootLee commented on pubspec.yaml
> +description: Flutter app for Kenya's 3rd Android Developer Conference - droidcon
why the space though

2022-10-04 11:33 UTC, KendiJ approved these changes

2022-10-04 15:52 UTC, EricRootLee approved these changes

2022-10-04 15:53 UTC, merged